project:
    type: book
    output-dir: "../build"

book:
    title: "NetCDFTools"
    author: 
        name: "Dongdong Kong"
        email: "kongdd@users.noreply.github.com"
    date: "2025-06-29"
    chapters:
        - index.md
        - api/1-SpatRaster.qmd
        - api/z-index.qmd 
        - Reference.md

    navbar: 
        background: primary
        right: 
        - text: Version
          menu: 
            - text: dev
        
    search: 
        location: sidebar
        type: textbox

    twitter-card: true
    open-graph: true
    repo-url: https://github.com/jl-pkgs/NetCDFTools.jl
    repo-actions: [issue]

toc-title: "Table of Contents"

execute:
    echo: false
    output: true
    cache: false
    freeze: false

bibliography: references.bib

format:
    html:
        include-in-header: 
            file: _static/versions.html
        code-link: true
        number-sections: false
        css: _static/style.css
        resources: 
            - _static/style.css
            - _static/versions.html
            - _static/theme.scss
        theme: 
            light: 
                - _static/theme.scss
                - default
            dark: 
                - _static/theme.scss
                - darkly
    